src/values/expressions/TaggedTemplateExpression.js
src/values/expressions/index.js
tests/src/getPropLiteralValue.js
tests/src/getPropValue.js

I most likely got this completely wrong, I'm far from being an AST connoisseur. At least, this prevents a crash in the meantime. It totally ignores the template tag, I'm not sure if there is a better way around that statically.

Added rudimentary support for `TaggedTemplateExpression`

---

__tests__/src/elementType-test.js
src/elementType.js

[fix] - Fix resolving element type with multiple member expressions.

---

package.json

Correct me if I am wrong, but it does not seem to be used [outside of tests](https://github.com/evcohen/jsx-ast-utils/blob/efff839e8be73e2028837284de51f9f8b37ce7cf/__tests__/helper.js#L3).

Move `acorn-jsx` to `devDependencies`.

---

package.json

It was still listed as a dependency after https://github.com/evcohen/jsx-ast-utils/commit/93fdce184b3b8778c424986ca54d0284ec02f6ef.

Remove `object-assign`.

---

__tests__/src/getPropValue-test.js
src/values/expressions/index.js

I ran into this lovely little fatal while running a jsx-a11y rule. Seems super edge-casey, and yet, it blew up my eslint run :) I think solution should work. I added a test case.

Fixing fatal throw in getPropValue for ArrowFunctionExpression

---

__tests__/src/eventHandlers-test.js
__tests__/src/propName-test.js
package.json
src/propName.js

Currently, the return value of `propName` is nullable. It should be able to guarantee a return value all the time.

propName should always return a value

---

__tests__/helper.js
__tests__/src/getPropLiteralValue-test.js
__tests__/src/getPropValue-test.js
package.json
src/values/expressions/BindExpression.js
src/values/expressions/index.js

Add support for BindExpression.

---

__tests__/src/getPropLiteralValue-test.js
__tests__/src/getPropValue-test.js
src/values/expressions/TemplateLiteral.js

Fixes #40 
cc: @AlmeroSteyn is this the expectation?

Fix undefined bug for template strings.

---

__tests__/helper.js
__tests__/src/getPropValue-test.js
package.json
src/values/expressions/ObjectExpression.js

We hit at an issue properly parsing props that looked like
```jsx
<div foo={{ params: {...router.params}}} />
```
because the SpreadProperty doesn't have a key/value pair. Opting to ignore spread properties, but properly recurse over the key/values we _can_ parse.

Adding support for `objectRestSpread` within props

---

__tests__/src/getPropValue-test.js
src/values/expressions/ObjectExpression.js

A pattern like this:
```
<Link to={{ pathname: manageRoute, state: {...data}}} />
```
Will cause `ObjectExpression` to throw an error. This diff properly treats `ExperimentalSpreadProperty` as a `SpreadProperty`.

[evcohen/eslint-plugin-jsx-a11y#399] Accommodate ExperimentalSpreadProperty in prop values

---

__tests__/src/getPropValue-test.js
src/values/expressions/SpreadElement.js
src/values/expressions/index.js

Account for array `SpreadElement` nodes.
```
<div foo={[...this.props.params, bar]} />
```

[#73] Account for SpreadElement AST Nodes

---

__tests__/helper.js
__tests__/src/getPropLiteralValue-test.js
__tests__/src/getPropValue-test.js
elementType.js
src/elementType.js
src/getProp.js
src/hasProp.js
src/values/Literal.js
src/values/expressions/ArrayExpression.js
src/values/expressions/BinaryExpression.js
src/values/expressions/BindExpression.js
src/values/expressions/CallExpression.js
src/values/expressions/ConditionalExpression.js
src/values/expressions/LogicalExpression.js
src/values/expressions/MemberExpression.js
src/values/expressions/ObjectExpression.js
src/values/expressions/OptionalMemberExpression.js
src/values/expressions/TemplateLiteral.js
src/values/expressions/UnaryExpression.js
src/values/expressions/UpdateExpression.js
src/values/expressions/index.js

Support patterns like
```
<div foo={b?.c?.d;} />
```
I made the ESLint changes necessary to upgrade from Babel 6 to Babel 7, although the kept the old dependencies. The upgrade should be easy and now it'll be easier to test locally with Babel 7 and not get a ton of ESLint warnings (because ESLint will upgrade as well and start complaining about cyclical imports).

[evcohen/jsx-ast-utils#70] Support OptionalMemberExpression AST nodes

---

__tests__/helper.js
__tests__/src/getPropLiteralValue-test.js
__tests__/src/getPropValue-test.js
src/values/expressions/index.js

This PR aims to fix additional TS-related bugs that weren't handled as of #72. It's still a work in progress.

Support Typescript-specific nodes

---

__tests__/src/getPropLiteralValue-test.js
__tests__/src/getPropValue-test.js
src/values/expressions/index.js

Rather than chase down every new AST Node type, this module should just not throw when it encounters them. It doesn't need to throw; the error isn't one that should stop the program's execution.

Stop throwing errors when unknown AST nodes are encountered

---

__tests__/helper.js
__tests__/src/elementType-test.js
__tests__/src/getProp-test.js
__tests__/src/getPropLiteralValue-babelparser-test.js
__tests__/src/getPropLiteralValue-flowparser-test.js
__tests__/src/getPropValue-babelparser-test.js
__tests__/src/getPropValue-flowparser-test.js
__tests__/src/hasProp-test.js
__tests__/src/propName-test.js
package.json
src/values/expressions/TypeCastExpression.js
src/values/expressions/index.js

We need to test with the flow-parser to account for Flow casting syntax.
But the flow-parser doesn't parse `BindExpression` correctly. 
So I broke the `getPropValue` and `getPropLiteralValue` value tests into a Babel parser version and a Flow parser version.

Account for TypeCastExpression in the utils

---

CHANGELOG.md

2.2.1 / 2019-06-30
==================
- (improvement) Account for TypeCastExpression in the utils

Update CHANGELOG for 2.2.1

---

.babelrc
.eslintrc
__tests__/helper.js
__tests__/src/getProp-parser-test.js
__tests__/src/getProp-test.js
package.json
src/getProp.js

**Background**
We are working on a set of rules for our company. One of those rules is to use jsx spread to pass through properties:
```js
function MyImage({ src, alt }) {
return <img {...{ src, alt }} />
}
```
This caused a conflict with the `jsx-a11y/alt-text` rule.
Upon investigation I found two things:
- https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/399#issuecomment-450706007 - which indicated to me that I would need to step up if I wanted to solve this issue
- It can not be fixed in the `jsx-a11y` library (https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/src/rules/alt-text.js#L39)
**Considerations**
The `getProp` function is used by a lot of other utilities (in `jsx-a11y`, but also in other libraries). That makes the change quite tricky. The only way it would …

support retrieving props from a spread with object expression

---

.babelrc
.eslintrc
__tests__/helper.js
__tests__/src/getPropValue-babelparser-test.js
src/values/expressions/LogicalExpression.js
src/values/expressions/OptionalCallExpression.js
src/values/expressions/index.js

Fixes #98.
Nullish coalescing will first require we update to babel 7.

[New] add OptionalCallExpression

---

__tests__/src/elementType-test.js
__tests__/src/getProp-test.js
__tests__/src/getPropLiteralValue-babelparser-test.js
__tests__/src/getPropLiteralValue-flowparser-test.js
__tests__/src/getPropValue-babelparser-test.js
__tests__/src/getPropValue-flowparser-test.js
__tests__/src/hasProp-test.js
__tests__/src/index-test.js
__tests__/src/propName-test.js
package.json
src/values/expressions/CallExpression.js
src/values/expressions/ChainExpression.js
src/values/expressions/MemberExpression.js
src/values/expressions/index.js

Tests are currently failing on master.
This PR fixes those tests, but in so doing, causes a potential breaking change - CallExpressions now include the invocation parens, and when available, the arguments.
It's not yet clear if this will break eslint-plugin-jsx-a11y; i'll test it with that and hopefully that will help inform if this is breaking or not.
Fixes #103.

[Breaking] add `ChainExpression`; `CallExpression` now includes arguments

---

__tests__/src/getPropValue-flowparser-test.js
src/values/expressions/SequenceExpression.js
src/values/expressions/index.js

Fix for #95.
The prop value with an expression type of SequenceExpression could not be resolved.

Account for SequenceExpression in the utils

---

__tests__/src/getProp-parser-test.js
src/getProp.js

BREAKING CHANGE: Nodes don't return the non-standard node.start & node.end anymore
As discussed in https://github.com/jsx-eslint/jsx-ast-utils/pull/97#issuecomment-630429265, this is the PR with the breaking change of not providing `node.start` & `node.end` anymore.

[Breaking]: Don't return node.start & node.end

---

.eslintignore
src/values/expressions/TSNonNullExpression.js
src/values/expressions/index.js

Adds project name in the error logs of unexpected nodes.
Currently it is not clear which utility is logging these errors. I've seen couple of reports where developers (including myself) were not sure where bug reports should be filed to.

[patch] include project name in error logging

---

CHANGELOG.md
__tests__/src/getPropValue-babelparser-test.js
src/values/expressions/TSNonNullExpression.js

Came here from a warning emitted by `eslint-plugin-jsx-a11y` in our (@waldoapp) codebase.

[Fix] Handle `as` casts in `TSNonNullExpression`

---

__tests__/src/getPropLiteralValue-babelparser-test.js
src/values/expressions/index.js

Just like a `MemberExpression`, the literal value of a `ChainExpression` should be a noop, otherwise it returns the expression itself as if it were a string.

The literal value for a ChainExpression should be a noop
